site_name: Docs
site_url: https://felixholfelder.github.io/docs/
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  language: de
  features:
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.share
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
